In [1]:
import numpy as np

np.random.seed(0)

### Exercise 1: Create an Array with Standard Normal Distribution

Imagine you want to initialize a random time series dataset. Where you have $N$ time series, each with length $L$ and you observe $P$ feature values in each time step. Initialize such a time series dataset $X$ with shape $(N, L, P)$ where each value follows a standard normal distribution

In [2]:
N = 8
L = 4
P = 2

X = np.random.randn(N, L, P)


assert X.shape == (N, L, P)
assert np.allclose(X[0,0,0], 1.764052345967664)

### Exercise 2: Reshape

When writing deep learning code, you may find that you will use the heuristics of shape matching to make code work, especially when writing backprop. Such heuristics would guide you to the right direction in a lot of cases, but could also sometimes be wrong. You need to be careful about what `reshape` is really doing under the hood. We want to give you such a flavor in this exercise.

Imagine now you come up with an interesting operation on this dataset, which is to combine every two adjacent time series, so that you will still have $L$ time steps but only $N / 2$ time series and $2P$ feature values in each time series. Think about how to implement this.

In [3]:
new_X = np.empty((N//2, L, 2*P))
for i in range(N//2):
    new_X[i, :, :P] = X[2*i, :, :]
    new_X[i, :, P:] = X[2*i + 1, :, :]


# The third feature value is the second time series's first feature value
assert new_X[0][0][2] == X[1][0][0]

### Exercise 3: Mystery of Broadcast

You will not need to write code in this exercise.

You may sometimes find it confusing when broadcasting is possible. So in this exercise, we would like you to have a flavor about this and think about the rule of broadcast in NumPy. The general rule is that starting from the right most dimension, and two arrays are compatible with broadcasting if (1) they are equal; (2) one of them is 1. Please find more details in the documentation about broadcasting rules here: https://numpy.org/doc/stable/user/basics.broadcasting.html

In [7]:
# Think about whether the following operations are possible for broadcasting
# If not, think about why
np.ones((2,3)) + np.ones((2,1))  #可以广播
np.ones((2,3)) + np.ones((1,3))  #可以广播

# Why only one of them works?
np.ones((32, 32, 3)) + np.ones((3,))  #可以广播
np.ones((32, 32, 3)) + np.ones((32,)) #不可以广播，会报错


[[2. 2. 2.]
 [2. 2. 2.]]
#
[[2. 2. 2.]
 [2. 2. 2.]]
#
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  ...
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  ...
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  ...
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 ...

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  ...
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  ...
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  ...
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]
#


ValueError: operands could not be broadcast together with shapes (32,32,3) (32,) 