# Recitation 0C - Fundamentals of NumPy

## Table of Contents
1. What is NumPy?
2. Installation
3. Initialization
4. Accessing
5. Modifying data
6. Pivoting data
7. Combining data
8. Math operations

## 1. What is NumPy?

NumPy is the fundamental package for scientific computing in Python.
It is a Python library that provides and an assortment of operations for fast operations on arrays - from mathematical, logical operations to basic linear algebra, random simulation and much more.

## 2. Installation
Generally NumPy is pre-installed on CoLab/AWS. You should first check if NumPy is available and its version.

To manually install Numpy, please follow the instructions below.

In [ ]:
# Check the installation of NumPy
!pip show numpy

# Install NumPy
!pip install numpy

# Import NumPy
import numpy as np

Name: numpy
Version: 1.23.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: /usr/local/lib/python3.10/dist-packages
Requires: 
Required-by: albumentations, altair, arviz, astropy, autograd, blis, bokeh, chex, cmdstanpy, contourpy, cufflinks, cvxpy, datascience, db-dtypes, dopamine-rl, ecos, flax, folium, gensim, gym, h5py, holoviews, hyperopt, imageio, imbalanced-learn, imgaug, jax, jaxlib, librosa, lightgbm, matplotlib, matplotlib-venn, missingno, mizani, ml-dtypes, mlxtend, moviepy, music21, nibabel, numba, numexpr, opencv-contrib-python, opencv-python, opencv-python-headless, opt-einsum, optax, orbax-checkpoint, osqp, pandas, pandas-gbq, patsy, plotnine, prophet, pyarrow, pycocotools, pyerfa, pymc, pytensor, python-louvain, PyWavelets, qdldl, qudida, scikit-image, scikit-learn, scipy, scs, seaborn, shapely, sklearn-pandas, soxr, spacy, statsmodels, tabl

## 3. Initialization

### a. Intrinsic NumPy array creation functions


#### 1D array creation functions

In [ ]:
# return evenly spaced values within a given interval
range_arr = np.arange(10)
print("An array given range is \n", range_arr, " with dimensions ", range_arr.shape, "\n")

# return evenly spaced numbers over a specified interval
linspace_arr = np.linspace(2.0, 3.0, num=5, endpoint=False)
print("An evenly spaced array given range is \n", linspace_arr, " with dimensions ", linspace_arr.shape, "\n")

An array given range is 
 [0 1 2 3 4 5 6 7 8 9]  with dimensions  (10,) 

An evenly spaced array given range is 
 [2.  2.2 2.4 2.6 2.8]  with dimensions  (5,) 



#### General ndarray creation functions

In [ ]:
# initialize an empty array with size 2 x 2
empty_arr = np.empty((2, 2))
print("An empty array is \n", empty_arr, " with dimensions ", empty_arr.shape, "\n")

# initialize an all zero array with size 2 x 3
zeros_arr = np.zeros((2, 3))
print("A zeros array is \n", zeros_arr, " with dimensions ", zeros_arr.shape, "\n")

# initialize an all one array with size 4 x 2
ones_arr = np.ones((4, 2))
print("A ones array is \n", ones_arr, " with dimensions ", ones_arr.shape, "\n")

An empty array is 
 [[4.64474102e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]  with dimensions  (2, 2) 

A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]]  with dimensions  (2, 3) 

A ones array is 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]  with dimensions  (4, 2) 



In [ ]:
# return an array of zeros with the same shape and type as a given array
zeros_like_arr = np.zeros_like(ones_arr)
print("A zero like array is \n", zeros_like_arr, " with dimensions ", zeros_like_arr.shape, "\n")

# return an array of ones with the same shape and type as a given array
ones_like_arr = np.ones_like(zeros_arr)
print("A ones like array is \n", ones_like_arr, " with dimensions ", ones_like_arr.shape, "\n")

A zero like array is 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]  with dimensions  (4, 2) 

A ones like array is 
 [[1. 1. 1.]
 [1. 1. 1.]]  with dimensions  (2, 3) 



In [ ]:
# return a new array of given shape and type, filled with fill_value
tens_arr = np.full((2,2), 10)
print("A filled array is \n", tens_arr, " with dimensions ", tens_arr.shape, "\n")

# Return a full array with the same shape and type as a given array.
full_like_arr = np.full_like(zeros_arr, 0.1, dtype=np.double)
print("A full like array is \n", full_like_arr, " with dimensions ", full_like_arr.shape, "\n")

A filled array is 
 [[10 10]
 [10 10]]  with dimensions  (2, 2) 

A full like array is 
 [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]  with dimensions  (2, 3) 



### b. Create an array from existing data

#### Conversion from other Python structures (i.e. lists and tuples)

In [ ]:
# initialize an array with the given list
new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print("An array from given list is \n", arr_from_list, " with dimensions ", arr_from_list.shape, "\n")

An array from given list is 
 [1 2 3 4]  with dimensions  (4,) 



#### Reading arrays from disk

In [ ]:
# initialize an array by loading data from a txt file
#txt_arr = np.loadtxt(path_to_txt_file)

# initialize an array by loading data from a npy file
#loaded_arr = np.load(path_to_npy_file)

### c. Use of special library functions (e.g., random)

In [ ]:
a = np.random.randint(0, 10, size = (1,4))
print("Random integer array", a, "of shape ", a.shape)

np.random.seed(0)
a = np.random.randint(0, 10, size = (1,4))
print("Random integer array with seed", a, "of shape ", a.shape)

Random integer array [[3 5 4 7]] of shape  (1, 4)
Random integer array with seed [[5 0 3 3]] of shape  (1, 4)


In [ ]:
# create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)
uniform_rand_arr = np.random.rand(3,2)
print("A random array from a uniform distribution is \n", uniform_rand_arr, " with dimensions ", uniform_rand_arr.shape, "\n")

# For random samples from N(\mu, \sigma^2), use:
# sigma * np.random.randn(...) + mu
mu = 3
sigma =2.5
sample_normal_arr = mu + sigma * np.random.randn(2, 4)
print("A random array from a gaussian distribution is \n", sample_normal_arr)
print("with mu: ", mu)
print("with sigma: ", sigma)
print("with dimensions ", sample_normal_arr.shape)

A random array from a uniform distribution is 
 [[0.84725174 0.6235637 ]
 [0.38438171 0.29753461]
 [0.05671298 0.27265629]]  with dimensions  (3, 2) 

A random array from a gaussian distribution is 
 [[ 6.41366795  2.7557607  -3.06488643  1.8673605 ]
 [ 1.82307249  5.43253999 -0.19537279  6.5934267 ]]
with mu:  3
with sigma:  2.5
with dimensions  (2, 4)


## 4. Accessing data

### a. Indexing: Accessing values from Numpy Arrays

In [ ]:
n = np.random.rand(4, 5, 6) # see this as 4 batches, each containing 5 rows and 6 columns
n

n[0, 2, 3] # returns the element located in the fourth column of third row of the first batch.

0.609177581558388

### b. Slicing: Accessing subsections of Numpy Arrays based on Indices

In [ ]:
# slice along a batch
print(n[0, :, :]) # same as: n[0]

print(n[0, 0:3, 0:4])

# slice along multiple batches
print(n[:, 3, 4]) # returns the elements in the 4th row and 5th column across all batches

[[0.95715516 0.14035078 0.87008726 0.47360805 0.80091075 0.52047748]
 [0.67887953 0.72063265 0.58201979 0.53737323 0.75861562 0.10590761]
 [0.47360042 0.18633234 0.73691818 0.21655035 0.13521817 0.32414101]
 [0.14967487 0.22232139 0.38648898 0.90259848 0.44994999 0.61306346]
 [0.90234858 0.09928035 0.96980907 0.65314004 0.17090959 0.35815217]]
[[0.95715516 0.14035078 0.87008726 0.47360805]
 [0.67887953 0.72063265 0.58201979 0.53737323]
 [0.47360042 0.18633234 0.73691818 0.21655035]]
[0.44994999 0.971945   0.14644176 0.38346223]


In [ ]:
#syntax for slicing at interval is start:stop:step_size

print(n[0::2]) # slices from index 0 to the end of the dimension at intervals of 2

print(n[0::2, 1:4, 1::2]) # rows (2-5) and columns at an interval of 2, starting from 1

[[[9.68961765e-01 3.20997241e-01 2.21262685e-01 1.41263905e-01
   9.72599271e-02 9.84042241e-01]
  [2.60340928e-01 5.37022521e-01 4.47926172e-01 9.95690891e-02
   3.52311661e-01 4.69249174e-01]
  [8.41140130e-01 9.04647744e-01 3.75593838e-02 5.08315449e-01
   1.66847513e-01 7.79051020e-01]
  [8.64933296e-01 4.11396724e-01 1.39972585e-01 3.32223853e-02
   9.82574960e-01 3.73290751e-01]
  [4.20075370e-01 5.05881151e-02 3.65496106e-01 1.66279737e-02
   2.30742335e-01 7.64911699e-01]]

 [[8.52955659e-02 5.64183327e-02 4.87837704e-01 8.81004562e-01
   9.76404387e-01 6.17657916e-01]
  [5.42498775e-01 8.54613580e-01 7.43834545e-01 4.78596326e-01
   6.77081574e-01 6.07045061e-01]
  [7.14696936e-01 4.69497183e-01 4.56014623e-01 9.06418087e-01
   1.37220420e-01 2.29219323e-01]
  [8.81585399e-01 9.04424976e-01 6.45784599e-01 3.24682972e-01
   5.19711194e-01 5.53568650e-05]
  [3.11860221e-01 4.25451538e-01 8.85337660e-01 6.79879456e-01
   4.56129772e-01 4.83408617e-01]]]
[[[5.37022521e-01 9.956908

## 5. Modifying data

### Modify single values

In [ ]:
#When you assign an array or its elements to a new variable,
#you have to explicitly numpy.copy the array, otherwise the variable is a view into the original array.

n_copy = np.copy(n)

# check if values in the two arrays are the same before copy
print(n_copy[2, 4, 1] == n[2, 4, 1])

n_copy[2, 4, 1] = 0.005

# check if values in the two arrays are the same after copy
print(n_copy[2, 4, 1] == n[2, 4, 1])

True
False


### Modifying multiple values

In [ ]:
# check if values in the two arrays are the same before copy
print(f"Are the arrays the same before modification: {n_copy[2, 3] == n[2, 3]}")
print(f"Before modifying values: {n_copy[2, 3]}")

n_copy[2, 3] = 0.5

print(f"After modifying values: {n_copy[2, 3]}")

# check if values in the two arrays are the same after copy
print(f"Are the arrays the same after modification: {n_copy[2, 3] == n[2, 3]}")

Are the arrays the same before modification: [ True  True  True  True  True  True]
Before modifying values: [8.81585399e-01 9.04424976e-01 6.45784599e-01 3.24682972e-01
 5.19711194e-01 5.53568650e-05]
After modifying values: [0.5 0.5 0.5 0.5 0.5 0.5]
Are the arrays the same after modification: [False False False False False False]


## 6.Pivoting data

### a. Reshaping Arrays
Array reshaping is an operation that changes the shape of an array whilst maintaining the same data in the array.

For instance, reshaping from (3, 4, 5) -> (2, 5, 6) or from (3, 4, 5) -> (6, 10). A reshape operation is valid, so long as the product of the new shape specified matches the product of the old shape.

#### Reshaping within the same number of dimensions

In [ ]:
s = np.random.rand(3, 4, 5)
print(f"Original Shape: {s.shape}")

s.size

print(s)

Original Shape: (3, 4, 5)
[[[0.04561464 0.20915703 0.28691504 0.67726331 0.06303829]
  [0.55564924 0.00924007 0.8330381  0.98432943 0.70349478]
  [0.1816312  0.51239346 0.58044714 0.78754216 0.60647546]
  [0.21840285 0.45516882 0.87886974 0.49226824 0.71556116]]

 [[0.48615956 0.70854815 0.49814023 0.84455008 0.19434222]
  [0.77332601 0.97425866 0.86230978 0.78042665 0.98503228]
  [0.75356961 0.00404811 0.26947943 0.41049214 0.42822383]
  [0.29784182 0.40113234 0.12065699 0.98069967 0.40612049]]

 [[0.56921076 0.3436055  0.78887278 0.41137241 0.35927142]
  [0.39949891 0.30183088 0.77521978 0.92621293 0.32531031]
  [0.95287067 0.0139484  0.53346568 0.30458203 0.88286   ]
  [0.25062272 0.67741183 0.81042409 0.43214805 0.75213452]]]


In [ ]:
s1 = s.reshape(2, 6, 5)
print(f"Reshaped from s: {s1.shape}")

print(s1)

Reshaped from s: (2, 6, 5)
[[[0.04561464 0.20915703 0.28691504 0.67726331 0.06303829]
  [0.55564924 0.00924007 0.8330381  0.98432943 0.70349478]
  [0.1816312  0.51239346 0.58044714 0.78754216 0.60647546]
  [0.21840285 0.45516882 0.87886974 0.49226824 0.71556116]
  [0.48615956 0.70854815 0.49814023 0.84455008 0.19434222]
  [0.77332601 0.97425866 0.86230978 0.78042665 0.98503228]]

 [[0.75356961 0.00404811 0.26947943 0.41049214 0.42822383]
  [0.29784182 0.40113234 0.12065699 0.98069967 0.40612049]
  [0.56921076 0.3436055  0.78887278 0.41137241 0.35927142]
  [0.39949891 0.30183088 0.77521978 0.92621293 0.32531031]
  [0.95287067 0.0139484  0.53346568 0.30458203 0.88286   ]
  [0.25062272 0.67741183 0.81042409 0.43214805 0.75213452]]]


#### Reshaping to a different number of dimensions

In [ ]:
r = np.arange(120)

print(f"Original shape: {r.shape}")

print(r)

Original shape: (120,)
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]


In [ ]:
# (120,) -> (3, 4, 10)
r1 = r.reshape(3, 4, 10) # this can also be written as r.reshape((3, 4, 10))
print(f"Reshaped from r: {r1.shape}")

print(r1)

Reshaped from r: (3, 4, 10)
[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]]

 [[ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]]

 [[ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]]]


In [ ]:
# (3, 4, 10) -> (6, 20)
r2 = r1.reshape(6, 20)
print(f"Reshaped from r1: {r2.shape}")

print(r2)

Reshaped from r1: (6, 20)
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]]


### b. Transposing Arrays
The transpose operation reverses the order of an array. It switches the rows to columns and vice versa. In a multi-dimensional array, the transpose operation moves the data from one axis to another in the order specified in the transpose method.

In [ ]:
x=np.arange(50).reshape((5,10))
print("Shape of the original array", x.shape)
print("Original array\n", x)

x1=np.transpose(x)
print("Shape of the transposed array", x1.shape)
print("Transposed array\n", x1)

x.T

Shape of the original array (5, 10)
Original array
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
Shape of the transposed array (10, 5)
Transposed array
 [[ 0 10 20 30 40]
 [ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]
 [ 4 14 24 34 44]
 [ 5 15 25 35 45]
 [ 6 16 26 36 46]
 [ 7 17 27 37 47]
 [ 8 18 28 38 48]
 [ 9 19 29 39 49]]


array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44],
       [ 5, 15, 25, 35, 45],
       [ 6, 16, 26, 36, 46],
       [ 7, 17, 27, 37, 47],
       [ 8, 18, 28, 38, 48],
       [ 9, 19, 29, 39, 49]])

In [ ]:
w = np.arange(60).reshape((3, 4, 5))
w

print("Shape of the Original array", w.shape)
print("Original array\n", w)



Shape of the Original array (3, 4, 5)
Original array
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


#### Transpose without specifying axes

In [ ]:
# Original Shape: 3,4,5

w1 = np.transpose(w)  # 0->2, 1->1, 2->0   (0,1,2)->(2,1,0)
print("Shape of the transposed array", w1.shape)
print("Transposed array\n", w1)

Shape of the transposed array (5, 4, 3)
Transposed array
 [[[ 0 20 40]
  [ 5 25 45]
  [10 30 50]
  [15 35 55]]

 [[ 1 21 41]
  [ 6 26 46]
  [11 31 51]
  [16 36 56]]

 [[ 2 22 42]
  [ 7 27 47]
  [12 32 52]
  [17 37 57]]

 [[ 3 23 43]
  [ 8 28 48]
  [13 33 53]
  [18 38 58]]

 [[ 4 24 44]
  [ 9 29 49]
  [14 34 54]
  [19 39 59]]]


#### Transpose along specified axes

In [ ]:
w

# Original Shape: 3,4,5

w2 = np.transpose(w, axes=(0, 2, 1)) # 0, 1, 2
print("Shape of the transposed array", w2.shape)
print("Transposed array\n", w2)

# Original Shape: 3,4,5

w3 = np.transpose(w, axes=(1, 2, 0))
print("Shape of the transposed array", w3.shape)
print("Transposed array\n", w3)

Shape of the transposed array (3, 5, 4)
Transposed array
 [[[ 0  5 10 15]
  [ 1  6 11 16]
  [ 2  7 12 17]
  [ 3  8 13 18]
  [ 4  9 14 19]]

 [[20 25 30 35]
  [21 26 31 36]
  [22 27 32 37]
  [23 28 33 38]
  [24 29 34 39]]

 [[40 45 50 55]
  [41 46 51 56]
  [42 47 52 57]
  [43 48 53 58]
  [44 49 54 59]]]
Shape of the transposed array (4, 5, 3)
Transposed array
 [[[ 0 20 40]
  [ 1 21 41]
  [ 2 22 42]
  [ 3 23 43]
  [ 4 24 44]]

 [[ 5 25 45]
  [ 6 26 46]
  [ 7 27 47]
  [ 8 28 48]
  [ 9 29 49]]

 [[10 30 50]
  [11 31 51]
  [12 32 52]
  [13 33 53]
  [14 34 54]]

 [[15 35 55]
  [16 36 56]
  [17 37 57]
  [18 38 58]
  [19 39 59]]]


### c. Flattening Arrays
The flatten operation in Numpy collapses arrays of multiple dimensions into one dimension.


Different orders can be specified when flattening Numpy Arrays. See examples below.

In [ ]:
k = np.random.rand(5, 6)

k

array([[0.82960225, 0.37903377, 0.09654961, 0.25613958, 0.59193516,
        0.4764772 ],
       [0.48793457, 0.45851455, 0.52459262, 0.44201532, 0.85263492,
        0.43343897],
       [0.82687037, 0.50934207, 0.08637698, 0.66003986, 0.20659461,
        0.84727532],
       [0.68135913, 0.17836735, 0.06985902, 0.00968817, 0.89204966,
        0.13346521],
       [0.77919197, 0.92516343, 0.71517875, 0.49081861, 0.4694983 ,
        0.88270929]])

#### Flattening Arrays along the row (default order)

In [ ]:
k1 = k.flatten() # all rows are stacked on each other into a 1D array.
k1

k1.shape

(30,)

In [ ]:
k1

array([0.82960225, 0.37903377, 0.09654961, 0.25613958, 0.59193516,
       0.4764772 , 0.48793457, 0.45851455, 0.52459262, 0.44201532,
       0.85263492, 0.43343897, 0.82687037, 0.50934207, 0.08637698,
       0.66003986, 0.20659461, 0.84727532, 0.68135913, 0.17836735,
       0.06985902, 0.00968817, 0.89204966, 0.13346521, 0.77919197,
       0.92516343, 0.71517875, 0.49081861, 0.4694983 , 0.88270929])

#### Flattening Arrays along the column

In [ ]:
k2= k.flatten('F') # forms a 1D array where elements in a column are listed before moving to the next column.
k2

k2.shape

(30,)

In [ ]:
k2

array([0.82960225, 0.48793457, 0.82687037, 0.68135913, 0.77919197,
       0.37903377, 0.45851455, 0.50934207, 0.17836735, 0.92516343,
       0.09654961, 0.52459262, 0.08637698, 0.06985902, 0.71517875,
       0.25613958, 0.44201532, 0.66003986, 0.00968817, 0.49081861,
       0.59193516, 0.85263492, 0.20659461, 0.89204966, 0.4694983 ,
       0.4764772 , 0.43343897, 0.84727532, 0.13346521, 0.88270929])

In [ ]:
k

array([[0.82960225, 0.37903377, 0.09654961, 0.25613958, 0.59193516,
        0.4764772 ],
       [0.48793457, 0.45851455, 0.52459262, 0.44201532, 0.85263492,
        0.43343897],
       [0.82687037, 0.50934207, 0.08637698, 0.66003986, 0.20659461,
        0.84727532],
       [0.68135913, 0.17836735, 0.06985902, 0.00968817, 0.89204966,
        0.13346521],
       [0.77919197, 0.92516343, 0.71517875, 0.49081861, 0.4694983 ,
        0.88270929]])

#### Flattening Arrays using Numpy Reshape


In [ ]:
k4= k.reshape(-1)
k4

k4.shape

(30,)

In [ ]:
k4

array([0.82960225, 0.37903377, 0.09654961, 0.25613958, 0.59193516,
       0.4764772 , 0.48793457, 0.45851455, 0.52459262, 0.44201532,
       0.85263492, 0.43343897, 0.82687037, 0.50934207, 0.08637698,
       0.66003986, 0.20659461, 0.84727532, 0.68135913, 0.17836735,
       0.06985902, 0.00968817, 0.89204966, 0.13346521, 0.77919197,
       0.92516343, 0.71517875, 0.49081861, 0.4694983 , 0.88270929])

### d. Squeezing & Expanding Arrays

#### Squeezing Numpy Arrays

The squeeze operation allows reduction of numpy arrays axes by dropping a specified axis, so long as it is of **unit length**. The product of the shape (overall size of the array) remains the same.

In [ ]:
sq = np.random.rand(4, 1, 5)
print(f"Original Array: \n{sq}\n")
print(f"Shape of Original Array: {sq.shape}")

# transforms from (4, 1, 5) -> (4, 5)
sq1 = np.squeeze(sq)
print(f"Squeezed Array: \n {sq1}\n")
print(f"Shape of Squeezed Array: {sq1.shape}")

Original Array: 
[[[0.48841006 0.41456749 0.17411195 0.47528944 0.78364797]]

 [[0.55642943 0.15986708 0.14382937 0.64946303 0.5392236 ]]

 [[0.32568477 0.14701389 0.15987007 0.12941234 0.57892239]]

 [[0.09226017 0.91054472 0.08297175 0.80037846 0.87713097]]]

Shape of Original Array: (4, 1, 5)
Squeezed Array: 
 [[0.48841006 0.41456749 0.17411195 0.47528944 0.78364797]
 [0.55642943 0.15986708 0.14382937 0.64946303 0.5392236 ]
 [0.32568477 0.14701389 0.15987007 0.12941234 0.57892239]
 [0.09226017 0.91054472 0.08297175 0.80037846 0.87713097]]

Shape of Squeezed Array: (4, 5)


In [ ]:
# Squeezing specified axes

q2 = np.squeeze(sq, axis=1)
print(f"Specified axis Squeezed Array: \n {q2}\n")
print(f"Shape of Specified axis Squeezed Array: {q2.shape}")

Specified axis Squeezed Array: 
 [[0.48841006 0.41456749 0.17411195 0.47528944 0.78364797]
 [0.55642943 0.15986708 0.14382937 0.64946303 0.5392236 ]
 [0.32568477 0.14701389 0.15987007 0.12941234 0.57892239]
 [0.09226017 0.91054472 0.08297175 0.80037846 0.87713097]]

Shape of Specified axis Squeezed Array: (4, 5)


#### Unsqueezing (Expanding) Numpy Arrays
This is the direct opposite of squeezing. A new unit axis is inserted in specified position. Multiple unit axes can be inserted by using a tuple on the axis attribute of the `expand_dims` method.

In [ ]:
y = np.random.rand(4, 5)
print(f"Original Array: \n {y}\n")
print(f"Shape of Original Array: {y.shape}")

# transforms from (4, 5) -> (4, 1, 5)
y1 = np.expand_dims(y, axis=1)
print(f"Expanded Array: \n {y1}\n")
print(f"Shape of Expanded Array: {y1.shape}")

# transforms from (4, 5) -> (1, 4, 1, 5)
y2 = np.expand_dims(y, axis=(0, 2))
print(f"Multi-axes Expanded Array: \n {y2}\n")
print(f"Shape of Multi-axes Expanded Array: {y2.shape}")

Original Array: 
 [[0.09345946 0.42630588 0.47322067 0.58019711 0.71624417]
 [0.02706898 0.73139734 0.76696351 0.00976644 0.30828617]
 [0.23286547 0.50342743 0.95372138 0.5578113  0.09746869]
 [0.62167849 0.86302262 0.15763228 0.99242952 0.08500107]]

Shape of Original Array: (4, 5)
Expanded Array: 
 [[[0.09345946 0.42630588 0.47322067 0.58019711 0.71624417]]

 [[0.02706898 0.73139734 0.76696351 0.00976644 0.30828617]]

 [[0.23286547 0.50342743 0.95372138 0.5578113  0.09746869]]

 [[0.62167849 0.86302262 0.15763228 0.99242952 0.08500107]]]

Shape of Expanded Array: (4, 1, 5)
Multi-axes Expanded Array: 
 [[[[0.09345946 0.42630588 0.47322067 0.58019711 0.71624417]]

  [[0.02706898 0.73139734 0.76696351 0.00976644 0.30828617]]

  [[0.23286547 0.50342743 0.95372138 0.5578113  0.09746869]]

  [[0.62167849 0.86302262 0.15763228 0.99242952 0.08500107]]]]

Shape of Multi-axes Expanded Array: (1, 4, 1, 5)


## 7. Combining data

### a. Concatenation

A concatenation operation joins a sequence of arrays along an *existing* axis. All arrays must either have the same shape (except in the concatenating dimension) or be empty.

In [ ]:
# Concatenating Numpy Arrays

array1 = np.random.randint(3, size = (3, 2, 2))
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

array2 = np.random.randint(4, size = (3, 2, 2))
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")

concatenated_array1 = np.concatenate((array1, array2), axis = 0)
print("Concatenated array 1 is \n", concatenated_array1, "\n\n", "and the dimensions of the concatenated array 1 are: \n", concatenated_array1.shape)

concatenated_array2 = np.concatenate((array1, array2), axis = 1)
print("Concatenated array 2 is \n", concatenated_array2, "\n\n", "and the dimensions of the concatenated array 2 are: \n", concatenated_array2.shape)

concatenated_array3 = np.concatenate((array1, array2), axis = 2)
print("Concatenated array 3 is \n", concatenated_array3, "\n\n", "and the dimensions of the concatenated array 3 are: \n", concatenated_array3.shape)


Array 1 is 
 [[[1 2]
  [2 2]]

 [[2 2]
  [0 2]]

 [[0 0]
  [1 1]]]  with dimensions  (3, 2, 2) 

Array 2 is 
 [[[2 1]
  [0 3]]

 [[2 1]
  [3 0]]

 [[1 2]
  [1 2]]]  with dimensions  (3, 2, 2) 

Concatenated array 1 is 
 [[[1 2]
  [2 2]]

 [[2 2]
  [0 2]]

 [[0 0]
  [1 1]]

 [[2 1]
  [0 3]]

 [[2 1]
  [3 0]]

 [[1 2]
  [1 2]]] 

 and the dimensions of the concatenated array 1 are: 
 (6, 2, 2)
Concatenated array 2 is 
 [[[1 2]
  [2 2]
  [2 1]
  [0 3]]

 [[2 2]
  [0 2]
  [2 1]
  [3 0]]

 [[0 0]
  [1 1]
  [1 2]
  [1 2]]] 

 and the dimensions of the concatenated array 2 are: 
 (3, 4, 2)
Concatenated array 3 is 
 [[[1 2 2 1]
  [2 2 0 3]]

 [[2 2 2 1]
  [0 2 3 0]]

 [[0 0 1 2]
  [1 1 1 2]]] 

 and the dimensions of the concatenated array 3 are: 
 (3, 2, 4)


### b. Stacking

The stack operation joins a sequence of arrays along a *new* axis. The axis parameter specifies the index of the new axis in the dimensions of the result. For example, if axis = 0 it will be the first dimension and if axis = -1 it will be the last dimension. All arrays need to be of the same size.  The stacked array has one more dimension than the input arrays.

In [ ]:
# Stacking 1-d Arrays

array1 = np.array([1, 2, 3])
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

array2 = np.array([4, 5, 6])
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")


stacked_array1 = np.stack((array1, array2), axis = 0)
print("Stacked array 1 is \n", stacked_array1, " with dimensions ", stacked_array1.shape)

stacked_array2 = np.stack((array1, array2), axis = 1)
print("Stacked array 2 is \n", stacked_array2, " with dimensions ", stacked_array2.shape)

stacked_array3 = np.stack((array1, array2), axis = -1)
print("Stacked array 3 is \n", stacked_array3, " with dimensions ", stacked_array3.shape)

Array 1 is 
 [1 2 3]  with dimensions  (3,) 

Array 2 is 
 [4 5 6]  with dimensions  (3,) 

Stacked array 1 is 
 [[1 2 3]
 [4 5 6]]  with dimensions  (2, 3)
Stacked array 2 is 
 [[1 4]
 [2 5]
 [3 6]]  with dimensions  (3, 2)
Stacked array 3 is 
 [[1 4]
 [2 5]
 [3 6]]  with dimensions  (3, 2)


In [ ]:

# Stacking Numpy Arrays

array1 = np.random.randint(3, size = (3, 4, 5))
print("Array 1 has dimensions ", array1.shape, "\n")

array2 = np.random.randint(4, size = (3, 4, 5))
print("Array 2 has dimensions ", array2.shape, "\n")

stacked_array1 = np.stack((array1, array2), axis = 0)
print("Stacked array 1 has dimensions", stacked_array1.shape, "\n")

stacked_array2 = np.stack((array1, array2), axis = 1)
print("Stacked array 2 has dimensions", stacked_array2.shape, "\n")

stacked_array3 = np.stack((array1, array2), axis = 2)
print("Stacked array 3 has dimensions", stacked_array3.shape, "\n")

stacked_array4 = np.stack((array1, array2), axis = -1)
print("Stacked array 4 has dimensions", stacked_array4.shape, "\n")

Array 1 has dimensions  (3, 4, 5) 

Array 2 has dimensions  (3, 4, 5) 

Stacked array 1 has dimensions (2, 3, 4, 5) 

Stacked array 2 has dimensions (3, 2, 4, 5) 

Stacked array 3 has dimensions (3, 4, 2, 5) 

Stacked array 4 has dimensions (3, 4, 5, 2) 



## 8. Math operations

In this section we will cover some commonly used mathematical operations
1. Broadcasting
1. Point-wise/element-wise operations
1. Reduction operations
1. Comparison operations
1. Vector/Matrix operations
1. Tensordot

### a. Broadcasting

In [ ]:
# Broadcasting b/w arrays of different dimensions
# Note: When broadting two multi-dimensional tensors, match their corresponding dimensions beginning from the last dimension.
# All dimensions should either match or one of the arrays should have length 1 in that specific dimension

row_arr = np.random.rand(1,3)
print("A row array: \n", row_arr, " with dimensions ", row_arr.shape, "\n")
col_arr = np.random.rand(4,1)
print("A column array: \n", col_arr, " with dimensions ", col_arr.shape, "\n")

add_arr = row_arr + col_arr
print("row array + column array = ")
print(add_arr," with dimensions ", add_arr.shape, "\n")
mul_arr = row_arr * col_arr
print("row array * column array = ")
print(mul_arr," with dimensions ", mul_arr.shape, "\n")

A row array: 
 [[0.90773296 0.73988392 0.89806236]]  with dimensions  (1, 3) 

A column array: 
 [[0.67258231]
 [0.52893993]
 [0.30444636]
 [0.99796225]]  with dimensions  (4, 1) 

row array + column array = 
[[1.58031527 1.41246623 1.57064467]
 [1.43667289 1.26882385 1.42700229]
 [1.21217932 1.04433028 1.20250872]
 [1.90569521 1.73784617 1.89602461]]  with dimensions  (4, 3) 

row array * column array = 
[[0.61052513 0.49763284 0.60402086]
 [0.48013621 0.39135415 0.47502104]
 [0.276356   0.22525497 0.27341182]
 [0.90588323 0.73837622 0.89623233]]  with dimensions  (4, 3) 



### b. Element-wise operations

In [ ]:
rand_arr_1 = np.random.rand(2,3)
print("A random array1 : \n", rand_arr_1, " with dimensions ", rand_arr_1.shape, "\n")
rand_arr_2 = np.random.rand(2,3)
print("A random array2 : \n", rand_arr_2, " with dimensions ", rand_arr_2.shape, "\n")
scalar = 5.0

# Addition with Scalars
new_arr_1 = rand_arr_1 + scalar
print("random array1 + 5.0 =")
print(new_arr_1, "\n")

# Multiplication with Scalars
new_arr_2 = rand_arr_1 * scalar
print("random array1 * 5.0 =")
print(new_arr_2, "\n")

# Elementwise Addition of Arrays
new_arr_3 = rand_arr_1 + rand_arr_2
print("random array1 + random array2 =")
print(new_arr_3, "\n")

# Elementwise Multiplication of Arrays aka Hadmard Product
new_arr_4 = rand_arr_1 * rand_arr_2
print("random array1 * random array2 =")
print(new_arr_4, "\n") # also equivalent to np.multiply(array1, array2)

# Absolute value
new_arr_5 = np.abs(-10*rand_arr_1)
print("abs (-10 * random array1) =")
print(new_arr_5, "\n")

# Square root value
new_arr_6 = np.sqrt(rand_arr_1)
print('sqrt(random array1) = \n', new_arr_6, "\n")

A random array1 : 
 [[0.36218906 0.47064895 0.37824517]
 [0.97952693 0.17465839 0.327988  ]]  with dimensions  (2, 3) 

A random array2 : 
 [[0.68034867 0.06320762 0.60724937]
 [0.4776465  0.28399998 0.23841328]]  with dimensions  (2, 3) 

random array1 + 5.0 =
[[5.36218906 5.47064895 5.37824517]
 [5.97952693 5.17465839 5.327988  ]] 

random array1 * 5.0 =
[[1.81094529 2.35324475 1.89122587]
 [4.89763465 0.87329193 1.63994   ]] 

random array1 + random array2 =
[[1.04253772 0.53385657 0.98549455]
 [1.45717343 0.45865836 0.56640128]] 

random array1 * random array2 =
[[0.24641484 0.0297486  0.22968915]
 [0.46786761 0.04960298 0.0781967 ]] 

abs (-10 * random array1) =
[[3.62189059 4.70648949 3.78245175]
 [9.79526929 1.74658385 3.27988001]] 

sqrt(random array1) = 
 [[0.60182145 0.68603859 0.6150164 ]
 [0.98971053 0.41792151 0.57270237]] 



### c. Reduction

In [ ]:
rand_arr = np.random.rand(2,3)
print('random array: \n', rand_arr, "\n")

max_val = np.max(rand_arr)
print('Maximum value of array \n', max_val, "\n")
min_val = np.min(rand_arr)
print('Minimum value of array \n', min_val, "\n")

sum_val = np.sum(rand_arr)
print('Sum of array \n', sum_val, "\n")
max_idx = np.argmax(rand_arr, axis=0)
print('Maximum value\'s index of array along axis 0 \n', max_idx, "\n")
min_idx = np.argmin(rand_arr, axis=1)
print('Minimum value\'s index of array along axis 1 \n', min_idx, "\n")

mean_val = np.mean(rand_arr)
print('Mean value of array \n', mean_val, "\n")
std_val = np.std(rand_arr)
print('Standard deviation value of array \n', std_val, "\n")
norm_val = np.linalg.norm(rand_arr)
print('Norm value of array \n', norm_val, "\n")

random array: 
 [[0.51451274 0.36792758 0.45651989]
 [0.33747738 0.97049369 0.13343943]] 

Maximum value of array 
 0.9704936935959776 

Minimum value of array 
 0.13343943174560402 

Sum of array 
 2.7803707222042746 

Maximum value's index of array along axis 0 
 [0 1 0] 

Minimum value's index of array along axis 1 
 [1 2] 

Mean value of array 
 0.4633951203673791 

Standard deviation value of array 
 0.2561410183310268 

Norm value of array 
 1.2969423861959788 



### d. Comparision

In [ ]:
rand_arr_1 = np.random.rand(2,3)
print('random array1: \n', rand_arr_1, '\n')
rand_arr_2 = np.random.rand(2,3)
print('random array2: \n', rand_arr_2, '\n')

# Element-wise Comparison Operations
greater_compare = rand_arr_1 > rand_arr_2
print('random array1 > random array2')
print(greater_compare, '\n')

less_compare = rand_arr_1 < rand_arr_2
print('random array1 < random array2')
print(less_compare, '\n')

not_equal_compare = rand_arr_1 != rand_arr_2
print('random array1 != random array2')
print(not_equal_compare, '\n')

# Combining reduction operations with boolean arrays
print("any values for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).any(), "\n")

print("all values for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).all(), "\n")

print("any values along first axis for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).any(axis=0), "\n")

print("any values along second axis for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).any(axis=1), "\n")

print("any values for random array1 != random array2:")
print((rand_arr_1 != rand_arr_2).any(), "\n")

print("all values for random array1 != random array2:")
print((rand_arr_1 != rand_arr_2).all(), "\n")

random array1: 
 [[0.09680395 0.34339173 0.5910269 ]
 [0.65917647 0.39725675 0.99927799]] 

random array2: 
 [[0.351893   0.72140667 0.63758269]
 [0.81305386 0.97622566 0.88979366]] 

random array1 > random array2
[[False False False]
 [False False  True]] 

random array1 < random array2
[[ True  True  True]
 [ True  True False]] 

random array1 != random array2
[[ True  True  True]
 [ True  True  True]] 

any values for random array1 > random array2:
True 

all values for random array1 > random array2:
False 

any values along first axis for random array1 > random array2:
[False False  True] 

any values along second axis for random array1 > random array2:
[False  True] 

any values for random array1 != random array2:
True 

all values for random array1 != random array2:
True 



### e. Vector/Matrix operations

In [ ]:
# Vector x Vector
array1 = np.random.randn(3)
array2 = np.random.randn(3)

print('Array1 \n', array1, 'with dimension ', array1.shape, '\n')
print('Array2 \n', array2, 'with dimension ', array2.shape, '\n')

matmul_arr = np.matmul(array1, array2)
another_arr = array1@array2
print('Matmul of the two arrays can be derived by using np.matmul(array1, array2) \n', matmul_arr)
print("Matmul of the two arrays can also be derived by using array1@array2 \n", another_arr)
print('Dimensions of resulting product: \n', matmul_arr.shape)

# Matrix x Vector
array3 = np.random.randn(3, 4)
array4 = np.random.randn(4)

print('Array3 \n', array3, 'with dimension ', array3.shape, '\n')
print('Array4 \n', array4, 'with dimension ', array4.shape, '\n')

matmul_arr = np.matmul(array3, array4)
another_arr = array3@array4
print('Matmul of a vector and a matrix can be derived by using np.matmul(array3, array4) \n', matmul_arr)
print('Matmul of a vector and a matrix can also be derived by using array3@array4 \n', another_arr)
print('Dimensions of resulting product: \n', matmul_arr.shape)

# Matrix x Matrix

matrix1 = np.random.randint(4, size = (2, 3))
matrix2 = np.random.randint(4, size = (3, 2))

print('Matrix1 \n', matrix1, 'with dimension ', matrix1.shape, '\n')
print('Matrix2 \n', matrix2, 'with dimension ', matrix2.shape, '\n')

matmul_mat = np.matmul(matrix1, matrix2)
print('Matmul of two matrices can be derived by using np.matmul(matrix1, matrix2) \n', matmul_mat)
print('Dimensions of resulting product: \n', matmul_mat.shape, "\n")

Array1 
 [ 0.77140595  1.02943883 -0.90876325] with dimension  (3,) 

Array2 
 [-0.42431762  0.86259601 -2.65561909] with dimension  (3,) 

Matmul of the two arrays can be derived by using np.matmul(array1, array2) 
 2.9739977176266237
Matmul of the two arrays can also be derived by using array1@array2 
 2.9739977176266237
Dimensions of resulting product: 
 ()
Array3 
 [[ 1.51332808  0.55313206 -0.04570396  0.22050766]
 [-1.02993528 -0.34994336  1.10028434  1.29802197]
 [ 2.69622405 -0.07392467 -0.65855297 -0.51423397]] with dimension  (3, 4) 

Array4 
 [-1.01804188 -0.07785476  0.38273243 -0.03424228] with dimension  (4,) 

Matmul of a vector and a matrix can be derived by using np.matmul(array3, array4) 
 [-1.60873839  1.45242927 -2.97355464]
Matmul of a vector and a matrix can also be derived by using array3@array4 
 [-1.60873839  1.45242927 -2.97355464]
Dimensions of resulting product: 
 (3,)
Matrix1 
 [[3 1 0]
 [1 2 2]] with dimension  (2, 3) 

Matrix2 
 [[3 2]
 [1 0]
 [2 2]] with

In [ ]:
rand_mat_1 = np.random.rand(4,2)
rand_mat_2 = np.random.rand(2,3)
print('Matrix1 \n', rand_mat_1, 'with dimension ', rand_mat_1.shape, '\n')
print('Matrix2 \n', rand_mat_2, 'with dimension ', rand_mat_2.shape, '\n')

# dot product
dot_mat = np.dot(rand_mat_1, rand_mat_2)
another_mat = rand_mat_1@rand_mat_2
print('Dot product of two matrices can be derived by using np.dot(mat1, mat2) \n', dot_mat)
print('Dot product of two matrices can also be derived by using mat1@mat2 \n', another_mat)
print('Dimensions of resulting product: \n', dot_mat.shape)

a = np.ones([9, 5, 7, 4])
b = np.ones([9, 5, 4, 3])
print('array1 \'s dimension ', a.shape, '\n')
print('array2 \'s dimension ', b.shape, '\n')

# matmul with multi-dimenstion arrays
c = np.matmul(a,b)
print('Matmul of two multi-dimension arrays can be derived by using np.matmul(array1, array2) \n')
print('Dimensions of resulting product: \n', c.shape)

Matrix1 
 [[0.67138348 0.34471813]
 [0.71376687 0.6391869 ]
 [0.39916115 0.43176013]
 [0.6145277  0.07004219]] with dimension  (4, 2) 

Matrix2 
 [[0.82240674 0.65342116 0.72634246]
 [0.536923   0.11047711 0.40503561]] with dimension  (2, 3) 

Dot product of two matrices can be derived by using np.dot(mat1, mat2) 
 [[0.73723739 0.47677964 0.62727745]
 [0.93020083 0.5370059  0.77733264]
 [0.56009476 0.30851995 0.46480592]
 [0.54299898 0.40928346 0.47472715]]
Dot product of two matrices can also be derived by using mat1@mat2 
 [[0.73723739 0.47677964 0.62727745]
 [0.93020083 0.5370059  0.77733264]
 [0.56009476 0.30851995 0.46480592]
 [0.54299898 0.40928346 0.47472715]]
Dimensions of resulting product: 
 (4, 3)
array1 's dimension  (9, 5, 7, 4) 

array2 's dimension  (9, 5, 4, 3) 

Matmul of two multi-dimension arrays can be derived by using np.matmul(array1, array2) 

Dimensions of resulting product: 
 (9, 5, 7, 3)


### f. Tensordot

Understanding tensordot function will help you in writing succint code for your homeworks especially in Convolutional Neural Net assignment.

To give a brief overview:
We input the arrays and the respective axes along which the sum-reductions are intended. The axes that take part in sum-reduction are removed in the output and all of the remaining axes from the input arrays are spread-out as different axes in the output keeping the order in which the input arrays are fed.

To understand in depth please checkout: https://stackoverflow.com/questions/41870228/understanding-tensordot

In [ ]:
a = np.arange(60.).reshape(3,4,5)
b = np.arange(24.).reshape(4,3,2)
print('A \'s dimension ', a.shape, '\n')
print('B \'s dimension ', b.shape, '\n')

# compute tensor dot product along specified axes.
c = np.tensordot(a,b, axes=([1,0],[0,1]))
print("A⨂B =\n", c, ' with dimension', c.shape, '\n')

# this equals to
d = np.zeros((5,2))
for i in range(5):
  for j in range(2):
    for k in range(3):
      for n in range(4):
        d[i,j] += a[k,n,i] * b[n,k,j]
print("tensor dot is equal to sum over certain dimensions.\n")
print(c==d)

A 's dimension  (3, 4, 5) 

B 's dimension  (4, 3, 2) 

A⨂B =
 [[4400. 4730.]
 [4532. 4874.]
 [4664. 5018.]
 [4796. 5162.]
 [4928. 5306.]]  with dimension (5, 2) 

tensor dot is equal to sum over certain dimensions.

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]
